### ISSUE TITLE
Create a NuGet package

### ISSUE THREAD

**Issue by phrohdoh** [rix0rrr/beacon#1]
Hi @rix0rrr,

Over at [OpenRA](https://github.com/OpenRA/OpenRA/issues/8906#issuecomment-294287758) we have a proposal to use beacon for LAN discovery and a NuGet package would make consumption much easier.

Is this something you are interested in or would you accept a pull request adding this to the project?

**Comment by rix0rrr** [comment]
I'm not in a position to work on this right now, but I'll gladly accept a PR!

**Comment by rob-v** [comment]
Thanks, created PR #2.

**Comment by rix0rrr** [comment]
Alright, I've uploaded the package. Hope everything works as expected.

**Comment by rob-v** [comment]
Thanks a lot, but I realized now small changes were merged after the package creation. Do I create new PR with updated package? I assume there won't be new features needed soon again.

**Comment by rix0rrr** [comment]
Those will have been included in the publish though?

I did the package publish after merging PR#3.

**Comment by rob-v** [comment]
You're right. sorry.
